name: Python tster

on:
  schedule:
    - cron: '0 */6 * * *'      # هر ۶ ساعت
  workflow_dispatch:            # اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
      - name: 2. neofetch
        run: |
          sudo apt install neofetch
          neofetch
